# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='serves',
            new_name='servings',
        ),
    ]
