# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20170302_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='serving_size',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
